services:
  modbus-controller:
    image: jakerobb/modbus-eth-controller:latest@sha256:b130bc92c2607121611167e07f647c5b0be8d878236bfa2ec2470643e14b5c77
    ports:
      - "8080:8080"
    volumes:
      - ./modbus-programs:/etc/modbus:ro
