name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: jakerobb/modbus-eth-controller

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date -u +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Report remote image sizes by platform
        run: |
          curl -sSfL https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_Linux_x86_64.tar.gz | tar xz
          ./crane manifest ${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }} > manifest.json

          echo "### Remote image sizes by platform" >> $GITHUB_STEP_SUMMARY
          jq -r '.manifests[] | [.platform.architecture, .size] | @tsv' manifest.json | while IFS=$'\t' read -r arch size; do
            human=$(numfmt --to=iec --suffix=B "$size")
            echo "- $arch: \`$human\`" >> $GITHUB_STEP_SUMMARY
          done
